services:
  queue:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 21 1 --loglevel debug

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317"
      - "4318:4318"
      - "5775:5775/udp" # For Thrift compact protocol
      - "6831:6831/udp" # For Jaeger agent
      - "6832:6832/udp" # For Thrift binary protocol
      - "5778:5778" # For local agent admin
      - "16686:16686" # Jaeger UI
      - "14268:14268" # For collector
      - "14250:14250" # For gRPC
      - "9411:9411" # Zipkin compatibility
