services:
  queue:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 21 1 --loglevel debug
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
